"""Public exception facade for SpecStar."""

from specstar.types import (
    ArchiveTruncatedError,
    CannotModifyResourceError,
    DuplicateResourceError,
    MissingOperationContextError,
    PermissionDeniedError,
    PreconditionFailedError,
    ResourceConflictError,
    ResourceDecodeError,
    ResourceIDNotFoundError,
    ResourceIsDeletedError,
    ResourceNotFoundError,
    RevisionIDNotFoundError,
    RevisionNotFoundError,
    RevisionNotMigratedError,
    SchemaConflictError,
    SpecStarWarning,
    UnindexedQueryError,
    UniqueConstraintError,
    ValidationError,
)

__all__ = [
    "ArchiveTruncatedError",
    "CannotModifyResourceError",
    "DuplicateResourceError",
    "MissingOperationContextError",
    "PermissionDeniedError",
    "PreconditionFailedError",
    "ResourceConflictError",
    "ResourceDecodeError",
    "ResourceIDNotFoundError",
    "ResourceIsDeletedError",
    "ResourceNotFoundError",
    "RevisionIDNotFoundError",
    "RevisionNotFoundError",
    "RevisionNotMigratedError",
    "SchemaConflictError",
    "SpecStarWarning",
    "UniqueConstraintError",
    "UnindexedQueryError",
    "ValidationError",
]
